<?php

namespace Sdis\VehiculeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CalendrierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalendrierRepository extends EntityRepository
{
    public function findForJson(\DateTime $dateDebut, \DateTime $dateFin){
        $qb = $this->createQueryBuilder('c')
            ->where('c.dateDebut BETWEEN :dateDebut and :dateFin')
            ->setParameter('dateDebut', $dateDebut)
            ->setParameter('dateFin', $dateFin);
        
        return $qb->getQuery()->getResult();
    }
    public function findForAffichage(\DateTime $date) {
        $dateFin = clone $date;
        $date->setTime(00,00);
        $dateFin->setTime(23,59);
        $qb = $this->createQueryBuilder('c')->where('c.dateDebut BETWEEN :dateDebut and :dateFin')
            ->setParameter('dateDebut', $date)
            ->setParameter('dateFin', $dateFin);
        
        return $qb->getQuery()->getResult();
    }
}
